version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: urbangold_db
    restart: always
    environment:
      POSTGRES_DB: urbangold
      POSTGRES_USER: ug_user
      POSTGRES_PASSWORD: ug_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  backend:
    build: ./backend
    container_name: urbangold_backend
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-g1a6z)(=@lpb5nt!my+a+e#2z%f5234nx1pz#yf)s3_6d-5d3&
      - DATABASE_URL=postgres://ug_user:ug_password@db:5432/urbangold
      - ALLOWED_HOSTS=*
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"

  frontend:
    build: ./frontend
    container_name: urbangold_frontend
    restart: always
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: urbangold_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/usr/share/nginx/html/django_static:ro
      - media_volume:/usr/share/nginx/html/media:ro
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume:
  media_volume:
